import type { Metadata } from "next";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";
import { ReactNode } from "react";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = async ({ children }: { children: ReactNode }) => {
  const session = await auth();
  return (
    <html lang="en">
      {/* <SessionProvider session={session}> */}
        <body
          className={` antialiased`}
        >
          {children}
          <Toaster />
        </body>
      {/* </SessionProvider> */}
    </html>
  );
}
export default RootLayout;